[package]
name = "scbuf"
version = "0.1.1"
license = "MIT"
description = "scbuf (sync circular buffer) is a Send and Sync, lock-free circular buffer implementation."
repository = "https://github.com/derMihai/scbuf"
readme = "README.md"
authors = ["Mihai Renea"]

[dependencies]
